AWSTemplateFormatVersion: '2010-09-09'
Description: 'Meu Laboratorio de IAM Least Privilege'

Resources:
  AdminUser:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: 'usr-lab-admin'

  ReadOnlyUser:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: 'usr-lab-auditor'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/ReadOnlyAccess'

  LabS3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub 'lab-least-privilege-data-${AWS::AccountId}'

  S3OperatorUser:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: 'usr-lab-s3-operator'

  S3RestrictedPolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: 'policy-s3-restricted-operator'
      Users:
        - !Ref S3OperatorUser
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Action:
              - 's3:ListBucket'
            Resource: !GetAtt LabS3Bucket.Arn
          - Effect: 'Allow'
            Action:
              - 's3:GetObject'
            Resource: !Sub '${LabS3Bucket.Arn}/*'
